//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurortPark.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудник
    {
        public string Код_сотрудника { get; set; }
        public string Должность { get; set; }
        public string ФИО_ { get; set; }
        public string Логин_ { get; set; }
        public string Пароль { get; set; }
        public string Последний_вход { get; set; }
        public string Тип_входа { get; set; }
    
        public virtual Пользователь Пользователь { get; set; }
    }
}
